// Independently authored facts; never generated by the context builder or model.
export const comparisonContext = `
Product: SBL-CSR-R2 — Coldstart Rack Controller R2; category Compute.
Wholesale price: $2,250.00 per controller; case pack 4; standard lead time 90 days.
Available to promise as of 2026-09-02: 0. Inbound: 48. Expected restock: 2026-12-03.
Product: SBL-RPC-12 — Redline Power Cell R12; category Power.
Wholesale price: $680.00 per cell; case pack 8; standard lead time 18 days.
Available to promise as of 2026-09-02: 312. Inbound: 0. Expected restock: none scheduled.
`;
